<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_pruduct</name>
   <tag></tag>
   <elementGuidId>8d108da2-7984-41c7-b0b7-07c8f26d2588</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='/products'][contains(text(),'/')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='/products'][contains(text(),'/')]</value>
      <webElementGuid>3c1a7e0f-eb96-4540-9eb8-86d3678736cd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
